---
apiVersion: v1
kind: Namespace
metadata:
  name: exam-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-apps
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:invalid
        ports:
        - containerPort: 80
