---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  password: cGFzc3dk
  password-user: cGFzc3dk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  database: testindor
  user: juanito
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-env-file
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-file
  template:
    metadata:
      labels:
        app: mysql-file
    spec:
      containers:
      - name: mysql-file
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database 
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password-user