---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-vol
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      mysql: ready
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  volumes:
  - name: vol
    hostPath:
      path: /local-mysql
  containers:
  - name: container-pod-pvc
    image: nginx:alpine
    volumeMounts:
    - name: vol
      mountPath: /mysql
