apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
spec:
  storageClassName: standard #  kubectl get sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
