---
apiVersion: v1
kind: Namespace
metadata:
  name: cka-g
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: cka-g
spec:
  podSelector: {}
  policyTypes:
  - Ingress
