---
apiVersion: v1
kind: Namespace
metadata:
  name: cka-f
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: cka-f
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      release: "stable"
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-app
  namespace: cka-f
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    command: ["sh","-c","while true; do sleep 10; echo `date` >> /var/www/html/fecha.txt; done"]
    volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my1
  labels:
    release: "stable"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: /mnt/kki2
