---
apiVersion: v1
kind: Pod
metadata:
  name: heavy
  namespace: compute
spec:
  containers:
  - name: cpu-hog
    image: busybox
    command: ["sh","-c","while true; do :; done"]
    resources:
      requests:
        cpu: 70m
        memory: 10Mi
