---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: cpu-demo-ctr2
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"
