---
apiVersion: v1
kind: Namespace
metadata:
  name: epsilon
---
apiVersion: v1
kind: Pod
metadata:
  name: pending-app
  namespace: epsilon
spec:
  containers:
  - name: demo
    image: registry.k8s.io/pause:3.8
    resources:
      requests:
        cpu: 30m
