---
apiVersion: v1
kind: Namespace
metadata:
  name: zeta
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
  namespace: zeta
spec:
  podSelector: {}
  policyTypes:
  - Egress 
