---
apiVersion: v1
kind: Namespace
metadata:
  name: beta
---
apiVersion: v1
kind: Pod
metadata:
  name: init-order
  namespace: beta
spec:
  volumes:
    - name: vol
      hostPath:
        path: /mnt/init
  containers:
  - name: main
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    command: ["sh","-c","while true; do sleep 30; cat /data/status; done;"]
    volumeMounts:
      - name: vol
        mountPath: /data/
  initContainers:
  - name: first
    image: busybox:1.28
    command: ['sh', '-c', "sleep 10; echo READY > /data/status"]
    volumeMounts:
      - name: vol
        mountPath: /data/
  - name: second
    image: busybox:1.28
    command: ['sh', '-c', "for i in {1..100}; do sleep 1; if [ -f /data/status ]; then exit 0; fi; done; exit 1;"]
    volumeMounts:
      - name: vol
        mountPath: /data/
