---
apiVersion: v1
kind: Namespace
metadata:
  name: delta
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: delta
---
apiVersion: v1
kind: Pod
metadata:
  name: token-check
  namespace: delta
spec:
  containers:
  - image: nginx
    name: nginx
    command: ["sh","-c","ls -l /var/run/secrets/tokens; cat /var/run/secrets/tokens/vault-token;"]
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: app-sa
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
