---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-real-pvc
  namespace: drain-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # 👈 EVITA PROVISIONER
  resources:
    requests:
      storage: 500Mi

