---
apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  namespace: corp
  labels:
    job: worker
spec:
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh","-c","echo Processing job; sleep 5"]
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: propio
  namespace: corp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: corp
  name: propio
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: propiobin
  namespace: corp
subjects:
subjects:
- kind: ServiceAccount
  name: propio
roleRef:
  kind: Role 
  name: propio
  apiGroup: rbac.authorization.k8s.io
