---
apiVersion: v1
kind: Namespace
metadata:
  name: job-fail-lab
---
apiVersion: v1
kind: Pod
metadata:
  name: fail-once
  namespace: job-fail-lab
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:noexiste
    ports:
    - containerPort: 80
