---
apiVersion: v1
kind: Namespace
metadata:
  name: cron-lab
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup
  namespace: cron-lab
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
