---
apiVersion: v1
kind: Namespace
metadata:
  name: security
---
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-internal
  namespace: security
spec:
  podSelector: {}
