---
apiVersion: v1
kind: Namespace
metadata:
  name: token-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: token-lab
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: token-lab
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      command: ["sh","-c","ls -l /var/run/secrets/tokens; cat /var/run/secrets/tokens/vault-token | cut -c 1-10 ;"]
      volumeMounts:
      - mountPath: /var/run/secrets/tokens
        name: vault-token
  serviceAccountName: build-robot
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault


