---
apiVersion: v1
kind: Namespace
metadata:
  name: daemon-lab
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: daemon-lab
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: busybox:stable
        command: ["sh","-c","echo $MY_NODE_NAME;"]
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
