---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writers
  namespace: storage-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: writers
  template:
    metadata:
      labels:
        app: writers
    spec:
      containers:
      - name: app
        image: busybox
        command:
        - sh
        - -c
        - |
          while true; do
            echo "$(hostname) $(date)" >> /data/out.txt
            sleep 5
          done
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: shared-pvc

