---
apiVersion: v1
kind: Namespace
metadata:
  name: project-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: project-a
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Change port to 80"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        system: nginx-label
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.8-alpine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: project-a
  name: workload-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-reader-binding
  namespace: project-a
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: workload-reader
  apiGroup: rbac.authorization.k8s.io