---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bad-pvc
  namespace: storage-advanced
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  selector:
    matchLabels:
      disk: slow
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prebound
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  local:
    path: /mnt/prebound
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube-m04
  claimRef:
    namespace: storage-advanced
    name: wrong-pvc-name   # ❌ PVC NO EXISTE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wrong-pvc-name
  namespace: storage-advanced
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: storage-advanced
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube-m04
  containers:
    - name: myfrontend
      image: nginx
      command: ["sh","-c","while true; do echo `date` >> /var/www/html/fechas.txt; sleep 5; done"]
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: wrong-pvc-name
