---
apiVersion: v1
kind: Namespace
metadata:
  name: structure-exam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: structure-exam
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
